import { NextRequest, NextResponse } from "next/server";
import { createAdminClient } from "@/lib/supabase/server-admin";
import { requireAdmin } from "@/lib/auth/admin";
import { logAdminAction } from "@/lib/database/admin-audit";

const SELECT =
  "id, name, eventCode:event_code, status, createdAt:created_at, scoringSettings:scoring_settings, currentMysteryLimit:current_mystery_limit, maxAttempts:max_attempts";

const CODE_PATTERN = /^[A-Z0-9][A-Z0-9-]{2,23}$/;

/** Postgres unique violation — surfaced as a clean 409, never a raw message. */
const UNIQUE_VIOLATION = "23505";

function normaliseCode(raw: unknown): string | null {
  if (typeof raw !== "string") return null;
  const code = raw.trim().toUpperCase();
  return CODE_PATTERN.test(code) ? code : null;
}

export async function GET(request: NextRequest) {
  const authError = requireAdmin(request);
  if (authError) return authError;

  const supabase = createAdminClient();
  const { data: events, error } = await supabase
    .from("events")
    .select(SELECT)
    .order("created_at", { ascending: false });

  if (error) {
    return NextResponse.json({ error: "Could not load events" }, { status: 500 });
  }
  return NextResponse.json(
    { events: events || [] },
    { headers: { "Cache-Control": "no-store" } }
  );
}

/**
 * Create or update an event.
 *
 * Identity is the row `id`, not the join code. The old handler used the code
 * as the WHERE key, which made "change the join code" impossible to express at
 * all — and meant creating an event could only ever produce an autogenerated
 * code like EVENT-M4X2QP.
 */
export async function POST(request: NextRequest) {
  const authError = requireAdmin(request);
  if (authError) return authError;

  const body = await request.json().catch(() => ({}));
  const {
    id,
    name,
    eventCode,
    status,
    scoringSettings,
    maxAttempts,
    currentMysteryLimit,
  } = body;

  const supabase = createAdminClient();

  // ── update ──
  if (id) {
    const updates: Record<string, unknown> = {};
    if (name !== undefined) updates.name = String(name).slice(0, 120);
    if (status !== undefined) updates.status = status;
    if (scoringSettings !== undefined) updates.scoring_settings = scoringSettings;
    if (maxAttempts !== undefined) updates.max_attempts = maxAttempts;
    if (currentMysteryLimit !== undefined) {
      updates.current_mystery_limit = currentMysteryLimit;
    }

    if (eventCode !== undefined) {
      const code = normaliseCode(eventCode);
      if (!code) {
        return NextResponse.json(
          { error: "A join code is 3–24 characters, letters, numbers or dashes." },
          { status: 400 }
        );
      }
      updates.event_code = code;
    }

    const { data, error } = await supabase
      .from("events")
      .update(updates)
      .eq("id", id)
      .select(SELECT)
      .single();

    if (error) {
      if (error.code === UNIQUE_VIOLATION) {
        return NextResponse.json(
          { error: "That join code is already in use." },
          { status: 409 }
        );
      }
      return NextResponse.json({ error: "Could not update the event" }, { status: 500 });
    }

    logAdminAction(supabase, {
      action: "event.update",
      eventId: id,
      detail: { fields: Object.keys(updates) },
    });
    return NextResponse.json({ event: data });
  }

  // ── create ──
  const code = normaliseCode(eventCode);
  if (!code) {
    return NextResponse.json(
      { error: "Choose a join code: 3–24 characters, letters, numbers or dashes." },
      { status: 400 }
    );
  }

  const { data, error } = await supabase
    .from("events")
    .insert({
      name: (typeof name === "string" && name.trim()) || "New event",
      event_code: code,
      status: "draft",
      scoring_settings: scoringSettings || undefined,
      max_attempts: maxAttempts || 10,
      current_mystery_limit: currentMysteryLimit || 3,
    })
    .select(SELECT)
    .single();

  if (error) {
    if (error.code === UNIQUE_VIOLATION) {
      return NextResponse.json(
        { error: "That join code is already in use." },
        { status: 409 }
      );
    }
    return NextResponse.json({ error: "Could not create the event" }, { status: 500 });
  }

  logAdminAction(supabase, {
    action: "event.create",
    eventId: data.id,
    detail: { eventCode: code },
  });
  return NextResponse.json({ event: data }, { status: 201 });
}

/**
 * Delete an event. Teams and sessions cascade, but AI logs do not —
 * ai_interactions.session_id is ON DELETE SET NULL, so they must be removed
 * first or every deleted event leaves orphaned, un-attributable logs behind.
 */
export async function DELETE(request: NextRequest) {
  const authError = requireAdmin(request);
  if (authError) return authError;

  const id = request.nextUrl.searchParams.get("id");
  const confirm = request.nextUrl.searchParams.get("confirm");

  if (!id) {
    return NextResponse.json({ error: "id is required" }, { status: 400 });
  }

  const supabase = createAdminClient();
  const { data: event } = await supabase
    .from("events")
    .select("id, event_code, name")
    .eq("id", id)
    .maybeSingle();

  if (!event) {
    return NextResponse.json({ error: "Event not found" }, { status: 404 });
  }

  // Checked server-side so a mis-fired retry cannot delete an event.
  if (confirm !== event.event_code) {
    return NextResponse.json(
      { error: "Type the join code exactly to confirm." },
      { status: 400 }
    );
  }

  const { data: sessions } = await supabase
    .from("game_sessions")
    .select("id")
    .eq("event_id", id);
  const sessionIds = (sessions ?? []).map((s) => s.id);

  if (sessionIds.length > 0) {
    await supabase.from("ai_interactions").delete().in("session_id", sessionIds);
  }
  await supabase.from("events").delete().eq("id", id);

  logAdminAction(supabase, {
    action: "event.delete",
    detail: { eventCode: event.event_code, name: event.name, sessions: sessionIds.length },
  });

  return NextResponse.json({ success: true, deletedSessions: sessionIds.length });
}
